### PR TITLE
COMP: Fix -fpermissive error

### PR DESCRIPTION
**Pull request by jcfr**
This commit fixes a regression introduced in 81dc56d (removed deprecated QString::null).

It fixes errors like the following:

```
  /path/to/CTK-Qt5-build/QtSOAP/src/qtsoap.h:433:79: error: cannot call constructor ‘QString::QString’ directly [-fpermissive]
    433 |     void setMethod(const QString &name, const QString &url = QString::QString());
        |
```

### CODE REVIEW

**Comment by jcfr** [comment]
Closing. This is superseded by:
* https://github.com/commontk/QtSOAP/pull/12
